linters:
  enable:
  - bodyclose
  - depguard
  - dogsled
  - dupl
  - errcheck
  - errorlint
  - exhaustive
  - exportloopref
  - forbidigo
  - gci
  - gochecknoinits
  - goconst
  - gocritic
  - godot
  - godox
  - gofmt
  - goheader
  - goimports
  - gomoddirectives
  - gomodguard
  - goprintffuncname
  - gosec
  - gosimple
  - govet
  - importas
  - ineffassign
  - ireturn
  - lll
  - makezero
  - misspell
  - nakedret
  - nestif
  - nilnil
  - nlreturn
  - nolintlint
  - predeclared
  - promlinter
  - revive
  - staticcheck
  - stylecheck
  - tenv
  - testpackage
  - thelper
  - typecheck
  - unconvert
  - unparam
  - unused
  - whitespace
  - wrapcheck
  - wsl
linters-settings:
  godox:
    keywords:
      - FIXME
      - BUG
