version: "2"
linters:
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - errorlint
    - exhaustive
    - forbidigo
    - gochecknoinits
    - goconst
    - gocritic
    - godot
    - godox
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - importas
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilnil
    - nlreturn
    - nolintlint
    - predeclared
    - promlinter
    - revive
    - staticcheck
    - testpackage
    - thelper
    - unconvert
    - unparam
    - usetesting
    - whitespace
    - wrapcheck
    - wsl_v5
  settings:
    godox:
      keywords:
        - FIXME
        - BUG
    nestif:
      min-complexity: 6
    wrapcheck:
      extra-ignore-sigs:
        - elephantine.InvalidArgumentf(
        - (context.Context).Err(
        - github.com/ttab/elephantine/pg.WithTX(
        - github.com/ttab/elephantine/pg.JobLock).RunWithContext(
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        path: _test\.go
      - linters:
          - gosec
        path: jwt_dummy\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
