linters:
  enable:
  - bodyclose
  - copyloopvar
  - dogsled
  - dupl
  - errcheck
  - errorlint
  - exhaustive
  - forbidigo
  - gci
  - gochecknoinits
  - goconst
  - gocritic
  - godot
  - godox
  - gofumpt
  - goheader
  - goimports
  - gomoddirectives
  - gomodguard
  - goprintffuncname
  - gosec
  - gosimple
  - govet
  - importas
  - ineffassign
  - lll
  - makezero
  - misspell
  - nakedret
  - nestif
  - nilnil
  - nlreturn
  - nolintlint
  - predeclared
  - promlinter
  - revive
  - staticcheck
  - stylecheck
  - testpackage
  - thelper
  - typecheck
  - unconvert
  - unparam
  - unused
  - usetesting
  - whitespace
  - wrapcheck
  - wsl
linters-settings:
  wrapcheck:
    ignoreSigs:
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - errors.Join(
      - .Wrap(
      - .Wrapf(
      - .WithMessage(
      - .WithMessagef(
      - .WithStack(
      - .WithTX(
  nestif:
    min-complexity: 6
  godox:
    keywords:
      - FIXME
      - BUG
