CREATE TABLE IF NOT EXISTS upload(
       id uuid NOT NULL PRIMARY KEY,
       created_by text NOT NULL,
       created_at timestamptz NOT NULL,
       name text NOT NULL,
       meta jsonb NOT NULL
);

CREATE TABLE IF NOT EXISTS attached_object(
       document uuid NOT NULL,
       name text NOT NULL,
       created_by text NOT NULL,
       created_at timestamptz NOT NULL,
       meta jsonb NOT NULL,
       PRIMARY KEY(document, name)
);

CREATE TABLE event_outbox_item(
       id bigint GENERATED ALWAYS AS IDENTITY,
       event jsonb NOT NULL,
       PRIMARY KEY(id)
);

ALTER TABLE eventlog ALTER COLUMN 
    id SET GENERATED BY DEFAULT;

---- create above / drop below ----

DROP TABLE IF EXISTS event_outbox_item;
DROP TABLE IF EXISTS attached_object;
DROP TABLE IF EXISTS upload;
