// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: batch.go

package postgres

import (
	"context"
	"errors"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const aCLUpdate = `-- name: ACLUpdate :batchexec
INSERT INTO acl(uuid, uri, permissions)
VALUES ($1, $2, $3::text[])
       ON CONFLICT(uuid, uri) DO UPDATE SET
          permissions = $3::text[]
`

type ACLUpdateBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type ACLUpdateParams struct {
	UUID        uuid.UUID
	URI         string
	Permissions []string
}

func (q *Queries) ACLUpdate(ctx context.Context, arg []ACLUpdateParams) *ACLUpdateBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.UUID,
			a.URI,
			a.Permissions,
		}
		batch.Queue(aCLUpdate, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &ACLUpdateBatchResults{br, len(arg), false}
}

func (b *ACLUpdateBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *ACLUpdateBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
