// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package postgres

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Acl struct {
	Uuid        uuid.UUID
	Uri         string
	Permissions pgtype.Array[string]
}

type AclAudit struct {
	ID         int64
	Uuid       uuid.UUID
	Updated    pgtype.Timestamptz
	UpdaterUri string
	State      []byte
	Archived   bool
}

type ActiveSchema struct {
	Name    string
	Version string
}

type DeleteRecord struct {
	ID         int64
	Uuid       uuid.UUID
	Uri        string
	Version    int64
	Created    pgtype.Timestamptz
	CreatorUri string
	Meta       []byte
	Type       string
}

type Document struct {
	Uuid           uuid.UUID
	Uri            string
	Created        pgtype.Timestamptz
	CreatorUri     string
	Updated        pgtype.Timestamptz
	UpdaterUri     string
	CurrentVersion int64
	Deleting       bool
	Type           string
}

type DocumentLink struct {
	FromDocument uuid.UUID
	Version      int64
	ToDocument   uuid.UUID
	Rel          pgtype.Text
	Type         pgtype.Text
}

type DocumentSchema struct {
	Name    string
	Version string
	Spec    []byte
}

type DocumentStatus struct {
	Uuid       uuid.UUID
	Name       string
	ID         int64
	Version    int64
	Created    pgtype.Timestamptz
	CreatorUri string
	Meta       []byte
	Archived   bool
	Signature  pgtype.Text
}

type DocumentVersion struct {
	Uuid         uuid.UUID
	Version      int64
	Created      pgtype.Timestamptz
	CreatorUri   string
	Meta         []byte
	DocumentData []byte
	Archived     bool
	Signature    pgtype.Text
}

type Eventlog struct {
	ID        int64
	Event     string
	Uuid      uuid.UUID
	Timestamp pgtype.Timestamptz
	Type      pgtype.Text
	Version   pgtype.Int8
	Status    pgtype.Text
	StatusID  pgtype.Int8
	Acl       []byte
}

type Eventsink struct {
	Name          string
	Position      int64
	Configuration []byte
}

type Report struct {
	Name          string
	Enabled       bool
	NextExecution pgtype.Timestamptz
	Spec          []byte
}

type SchemaVersion struct {
	Version int32
}

type SigningKey struct {
	Kid  string
	Spec []byte
}

type Status struct {
	Name     string
	Disabled bool
}

type StatusHead struct {
	Uuid       uuid.UUID
	Name       string
	CurrentID  int64
	Updated    pgtype.Timestamptz
	UpdaterUri string
}

type StatusRule struct {
	Name        string
	Description string
	AccessRule  bool
	AppliesTo   pgtype.Array[string]
	ForTypes    pgtype.Array[string]
	Expression  string
}
